title: "Scholar2SQL Blog"
description: "Scholar2SQL automates data extraction from papers into an SQL database."
author: "Adrien Journé"
email: "adrien.journe@protonmail.com"
url: "https://bluebrain.github.io/scholar2sql/"

# Theme settings
theme: minima

# Enable dark mode support
minima:
  skin: dark

# Build settings
plugins:
  - jekyll-feed

markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/