title: "Scholar2SQL Blog"
description: "Scholar2SQL automates data extraction from papers into an SQL database."
author: "Adrien Journé"
email: "adrien.journe@protonmail.com"
url: "https://scholar2sql.github.io"

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/